Use --force to fix the error of package installation
---
checking for file conflicts...
error: failed to commit transaction (conflicting files)
expect: /usr/bin/mkpasswd exists in filesystem
Errors occurred, no packages were upgraded.
---